### ISSUE TITLE
Sections do not update the URL

### ISSUE THREAD

**Issue by richardgoater** [jyothishnt/PhyloCanvas-API-Site#5]
Hi Jyo, I'm noticing that the sections (Getting Started, Techincal Doc, etc.) do not update the URL of the page. Do you think it would be nice to add a something like `#getting-started` or `#technical-doc` to the end of the URL when clicking on the link, and also displaying the correct section when going directly to the page fragment?

This also leads me to think that the current fragment mechanism is not great for SEO, if we are concerned about that...

**Comment by jyothishnt** [comment]
Hi Rich, Thanks for pointing this issue. Adding fragment IDs to the url and loading the corresponding page is available now. I know SEO does not like these kind of page loads. Need to think about making them static if it is really a concern. But I agree that it would be useful.

**Comment by richardgoater** [comment]
Nice one mate! Is it available on the github pages version? Are you also able to put the github pages link in the readme please?

**Comment by jyothishnt** [comment]
Updated now. :) Thanks.

**Comment by richardgoater** [comment]
Cheers dude, closing this.
